name: Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Configure Git
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

        - name: Extract version
          id: get_version
          run: |
            VERSION="v$(jq -r '.version' theme.json)"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Get previous version
          id: get_prev_version
          run: |
            PREV_VERSION=$(git tag --sort=-v:refname | grep -v "^${VERSION}$" | head -n 1)
            echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV

        - name: Extract changelog
          id: get_changelog
          run: |
            CHANGELOG=$(awk -v version="$VERSION" '
              BEGIN { p=0 }
              $0 ~ "^### " version { p=1; next }
              /^### v/ { p=0 }
              p { print }
            ' CHANGELOG.md)
            CHANGELOG=$(echo "$CHANGELOG" | sed '/./,$!d')
            CHANGELOG=$(echo "$CHANGELOG" | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}')
            CHANGELOG=$(printf "%s\n\n**Full Changelog**: https://github.com/acolombo11/zero-notes-theme/compare/$PREV_VERSION...$VERSION" "$CHANGELOG")
            echo "CHANGELOG<<EOF" >> $GITHUB_ENV
            echo "$CHANGELOG" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

        - name: Zip Release
          uses: thedoctor0/zip-release@0.7.6
          with:
            type: 'zip'
            filename: 'package.zip'
            exclusions: '*.git* *.scss *.txt /*styles/* /*doc/* /*src/* *config* *package* /*scripts/* *CHANGELOG* /*.icon*'
    
        - name: Create Release
          uses: ncipollo/release-action@v1.13.0
          with:
            tag: ${{ env.VERSION }}
            allowUpdates: true
            artifactErrorsFailBuild: true
            artifacts: "package.zip"
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Update Release Notes
          uses: softprops/action-gh-release@v1
          with:
            body: ${{ env.CHANGELOG }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}